security:
    encoders:
        App\Entity\Account: bcrypt

    providers:
        my_provider:
            entity:
                class: App\Entity\Account
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            anonymous: true
            provider: my_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: redirection
                always_use_default_target_path: true
            logout:
                path: logout
                target: login

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_AGENT]

    access_control:
#        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/agent, role: ROLE_AGENT, requires_channel: https }
#        - { path: ^/footballer, role: ROLE_USER, requires_channel: https }
#        - { path: ^/admin, role: ROLE_ADMIN, requires_channel: https }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/agent, role: ROLE_AGENT }
        - { path: ^/footballer/, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
