twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        footballer_photo_directory: 'img/footballer/photo/'
        footballer_photo_compressed_directory: 'img/footballer/photo-compressed/'
        footballer_photo_profil_directory: 'img/footballer/photo-profil/'
        footballer_video_directory: 'video'
